// Code generated by forgegen from swagger.v1.json — DO NOT EDIT.

package types

import "time"

type Activity struct {
	ActUser   *User       `json:"act_user,omitempty"`
	ActUserID int64       `json:"act_user_id,omitempty"`
	Comment   *Comment    `json:"comment,omitempty"`
	CommentID int64       `json:"comment_id,omitempty"`
	Content   string      `json:"content,omitempty"`
	Created   time.Time   `json:"created,omitempty"`
	ID        int64       `json:"id,omitempty"`
	IsPrivate bool        `json:"is_private,omitempty"`
	OpType    string      `json:"op_type,omitempty"` // the type of action
	RefName   string      `json:"ref_name,omitempty"`
	Repo      *Repository `json:"repo,omitempty"`
	RepoID    int64       `json:"repo_id,omitempty"`
	UserID    int64       `json:"user_id,omitempty"`
}

// ActivityPub — ActivityPub type
type ActivityPub struct {
	Context string `json:"@context,omitempty"`
}
