// Code generated by forgegen from swagger.v1.json — DO NOT EDIT.

package types

import "time"

// Branch — Branch represents a repository branch
//
// Usage:
//
//	opts := Branch{EffectiveBranchProtectionName: "main"}
type Branch struct {
	Commit                        *PayloadCommit `json:"commit,omitempty"`
	EffectiveBranchProtectionName string         `json:"effective_branch_protection_name,omitempty"`
	EnableStatusCheck             bool           `json:"enable_status_check,omitempty"`
	Name                          string         `json:"name,omitempty"`
	Protected                     bool           `json:"protected,omitempty"`
	RequiredApprovals             int64          `json:"required_approvals,omitempty"`
	StatusCheckContexts           []string       `json:"status_check_contexts,omitempty"`
	UserCanMerge                  bool           `json:"user_can_merge,omitempty"`
	UserCanPush                   bool           `json:"user_can_push,omitempty"`
}

// BranchProtection — BranchProtection represents a branch protection for a repository
//
// Usage:
//
//	opts := BranchProtection{BranchName: "main"}
type BranchProtection struct {
	ApplyToAdmins                 bool      `json:"apply_to_admins,omitempty"`
	ApprovalsWhitelistTeams       []string  `json:"approvals_whitelist_teams,omitempty"`
	ApprovalsWhitelistUsernames   []string  `json:"approvals_whitelist_username,omitempty"`
	BlockOnOfficialReviewRequests bool      `json:"block_on_official_review_requests,omitempty"`
	BlockOnOutdatedBranch         bool      `json:"block_on_outdated_branch,omitempty"`
	BlockOnRejectedReviews        bool      `json:"block_on_rejected_reviews,omitempty"`
	BranchName                    string    `json:"branch_name,omitempty"` // Deprecated: true
	Created                       time.Time `json:"created_at,omitempty"`
	DismissStaleApprovals         bool      `json:"dismiss_stale_approvals,omitempty"`
	EnableApprovalsWhitelist      bool      `json:"enable_approvals_whitelist,omitempty"`
	EnableMergeWhitelist          bool      `json:"enable_merge_whitelist,omitempty"`
	EnablePush                    bool      `json:"enable_push,omitempty"`
	EnablePushWhitelist           bool      `json:"enable_push_whitelist,omitempty"`
	EnableStatusCheck             bool      `json:"enable_status_check,omitempty"`
	IgnoreStaleApprovals          bool      `json:"ignore_stale_approvals,omitempty"`
	MergeWhitelistTeams           []string  `json:"merge_whitelist_teams,omitempty"`
	MergeWhitelistUsernames       []string  `json:"merge_whitelist_usernames,omitempty"`
	ProtectedFilePatterns         string    `json:"protected_file_patterns,omitempty"`
	PushWhitelistDeployKeys       bool      `json:"push_whitelist_deploy_keys,omitempty"`
	PushWhitelistTeams            []string  `json:"push_whitelist_teams,omitempty"`
	PushWhitelistUsernames        []string  `json:"push_whitelist_usernames,omitempty"`
	RequireSignedCommits          bool      `json:"require_signed_commits,omitempty"`
	RequiredApprovals             int64     `json:"required_approvals,omitempty"`
	RuleName                      string    `json:"rule_name,omitempty"`
	StatusCheckContexts           []string  `json:"status_check_contexts,omitempty"`
	UnprotectedFilePatterns       string    `json:"unprotected_file_patterns,omitempty"`
	Updated                       time.Time `json:"updated_at,omitempty"`
}

// CreateBranchProtectionOption — CreateBranchProtectionOption options for creating a branch protection
//
// Usage:
//
//	opts := CreateBranchProtectionOption{BranchName: "main"}
type CreateBranchProtectionOption struct {
	ApplyToAdmins                 bool     `json:"apply_to_admins,omitempty"`
	ApprovalsWhitelistTeams       []string `json:"approvals_whitelist_teams,omitempty"`
	ApprovalsWhitelistUsernames   []string `json:"approvals_whitelist_username,omitempty"`
	BlockOnOfficialReviewRequests bool     `json:"block_on_official_review_requests,omitempty"`
	BlockOnOutdatedBranch         bool     `json:"block_on_outdated_branch,omitempty"`
	BlockOnRejectedReviews        bool     `json:"block_on_rejected_reviews,omitempty"`
	BranchName                    string   `json:"branch_name,omitempty"` // Deprecated: true
	DismissStaleApprovals         bool     `json:"dismiss_stale_approvals,omitempty"`
	EnableApprovalsWhitelist      bool     `json:"enable_approvals_whitelist,omitempty"`
	EnableMergeWhitelist          bool     `json:"enable_merge_whitelist,omitempty"`
	EnablePush                    bool     `json:"enable_push,omitempty"`
	EnablePushWhitelist           bool     `json:"enable_push_whitelist,omitempty"`
	EnableStatusCheck             bool     `json:"enable_status_check,omitempty"`
	IgnoreStaleApprovals          bool     `json:"ignore_stale_approvals,omitempty"`
	MergeWhitelistTeams           []string `json:"merge_whitelist_teams,omitempty"`
	MergeWhitelistUsernames       []string `json:"merge_whitelist_usernames,omitempty"`
	ProtectedFilePatterns         string   `json:"protected_file_patterns,omitempty"`
	PushWhitelistDeployKeys       bool     `json:"push_whitelist_deploy_keys,omitempty"`
	PushWhitelistTeams            []string `json:"push_whitelist_teams,omitempty"`
	PushWhitelistUsernames        []string `json:"push_whitelist_usernames,omitempty"`
	RequireSignedCommits          bool     `json:"require_signed_commits,omitempty"`
	RequiredApprovals             int64    `json:"required_approvals,omitempty"`
	RuleName                      string   `json:"rule_name,omitempty"`
	StatusCheckContexts           []string `json:"status_check_contexts,omitempty"`
	UnprotectedFilePatterns       string   `json:"unprotected_file_patterns,omitempty"`
}

// CreateBranchRepoOption — CreateBranchRepoOption options when creating a branch in a repository
//
// Usage:
//
//	opts := CreateBranchRepoOption{BranchName: "main"}
type CreateBranchRepoOption struct {
	BranchName    string `json:"new_branch_name"`           // Name of the branch to create
	OldBranchName string `json:"old_branch_name,omitempty"` // Deprecated: true Name of the old branch to create from
	OldRefName    string `json:"old_ref_name,omitempty"`    // Name of the old branch/tag/commit to create from
}

// EditBranchProtectionOption — EditBranchProtectionOption options for editing a branch protection
//
// Usage:
//
//	opts := EditBranchProtectionOption{ApprovalsWhitelistTeams: []string{"example"}}
type EditBranchProtectionOption struct {
	ApplyToAdmins                 bool     `json:"apply_to_admins,omitempty"`
	ApprovalsWhitelistTeams       []string `json:"approvals_whitelist_teams,omitempty"`
	ApprovalsWhitelistUsernames   []string `json:"approvals_whitelist_username,omitempty"`
	BlockOnOfficialReviewRequests bool     `json:"block_on_official_review_requests,omitempty"`
	BlockOnOutdatedBranch         bool     `json:"block_on_outdated_branch,omitempty"`
	BlockOnRejectedReviews        bool     `json:"block_on_rejected_reviews,omitempty"`
	DismissStaleApprovals         bool     `json:"dismiss_stale_approvals,omitempty"`
	EnableApprovalsWhitelist      bool     `json:"enable_approvals_whitelist,omitempty"`
	EnableMergeWhitelist          bool     `json:"enable_merge_whitelist,omitempty"`
	EnablePush                    bool     `json:"enable_push,omitempty"`
	EnablePushWhitelist           bool     `json:"enable_push_whitelist,omitempty"`
	EnableStatusCheck             bool     `json:"enable_status_check,omitempty"`
	IgnoreStaleApprovals          bool     `json:"ignore_stale_approvals,omitempty"`
	MergeWhitelistTeams           []string `json:"merge_whitelist_teams,omitempty"`
	MergeWhitelistUsernames       []string `json:"merge_whitelist_usernames,omitempty"`
	ProtectedFilePatterns         string   `json:"protected_file_patterns,omitempty"`
	PushWhitelistDeployKeys       bool     `json:"push_whitelist_deploy_keys,omitempty"`
	PushWhitelistTeams            []string `json:"push_whitelist_teams,omitempty"`
	PushWhitelistUsernames        []string `json:"push_whitelist_usernames,omitempty"`
	RequireSignedCommits          bool     `json:"require_signed_commits,omitempty"`
	RequiredApprovals             int64    `json:"required_approvals,omitempty"`
	StatusCheckContexts           []string `json:"status_check_contexts,omitempty"`
	UnprotectedFilePatterns       string   `json:"unprotected_file_patterns,omitempty"`
}

// UpdateBranchRepoOption — UpdateBranchRepoOption options when updating a branch in a repository
//
// Usage:
//
//	opts := UpdateBranchRepoOption{Name: "example"}
type UpdateBranchRepoOption struct {
	Name string `json:"name"` // New branch name
}
