// Code generated by forgegen from swagger.v1.json — DO NOT EDIT.

package types

import "time"


type Commit struct {
	Author *User `json:"author,omitempty"`
	Commit *RepoCommit `json:"commit,omitempty"`
	Committer *User `json:"committer,omitempty"`
	Created time.Time `json:"created,omitempty"`
	Files []*CommitAffectedFiles `json:"files,omitempty"`
	HTMLURL string `json:"html_url,omitempty"`
	Parents []*CommitMeta `json:"parents,omitempty"`
	SHA string `json:"sha,omitempty"`
	Stats *CommitStats `json:"stats,omitempty"`
	URL string `json:"url,omitempty"`
}

// CommitAffectedFiles — CommitAffectedFiles store information about files affected by the commit
type CommitAffectedFiles struct {
	Filename string `json:"filename,omitempty"`
	Status string `json:"status,omitempty"`
}

// CommitDateOptions — CommitDateOptions store dates for GIT_AUTHOR_DATE and GIT_COMMITTER_DATE
//
// Usage:
//
//	opts := CommitDateOptions{Author: time.Now()}
type CommitDateOptions struct {
	Author time.Time `json:"author,omitempty"`
	Committer time.Time `json:"committer,omitempty"`
}

type CommitMeta struct {
	Created time.Time `json:"created,omitempty"`
	SHA string `json:"sha,omitempty"`
	URL string `json:"url,omitempty"`
}

// CommitStats — CommitStats is statistics for a RepoCommit
type CommitStats struct {
	Additions int64 `json:"additions,omitempty"`
	Deletions int64 `json:"deletions,omitempty"`
	Total int64 `json:"total,omitempty"`
}

// CommitStatus — CommitStatus holds a single status of a single Commit
type CommitStatus struct {
	Context string `json:"context,omitempty"`
	Created time.Time `json:"created_at,omitempty"`
	Creator *User `json:"creator,omitempty"`
	Description string `json:"description,omitempty"`
	ID int64 `json:"id,omitempty"`
	Status CommitStatusState `json:"status,omitempty"`
	TargetURL string `json:"target_url,omitempty"`
	URL string `json:"url,omitempty"`
	Updated time.Time `json:"updated_at,omitempty"`
}

// CommitStatusState — CommitStatusState holds the state of a CommitStatus It can be "pending", "success", "error" and "failure"
type CommitStatusState string

type CommitUser struct {
	Date string `json:"date,omitempty"`
	Email string `json:"email,omitempty"`
	Name string `json:"name,omitempty"`
}
