// Code generated by forgegen from swagger.v1.json — DO NOT EDIT.

package types

import "time"

// Comment — Comment represents a comment on a commit or issue
//
// Usage:
//
//	opts := Comment{Body: "example"}
type Comment struct {
	Attachments      []*Attachment `json:"assets,omitempty"`
	Body             string        `json:"body,omitempty"`
	Created          time.Time     `json:"created_at,omitempty"`
	HTMLURL          string        `json:"html_url,omitempty"`
	ID               int64         `json:"id,omitempty"`
	IssueURL         string        `json:"issue_url,omitempty"`
	OriginalAuthor   string        `json:"original_author,omitempty"`
	OriginalAuthorID int64         `json:"original_author_id,omitempty"`
	PRURL            string        `json:"pull_request_url,omitempty"`
	Updated          time.Time     `json:"updated_at,omitempty"`
	User             *User         `json:"user,omitempty"`
}
