// Code generated by forgegen from swagger.v1.json — DO NOT EDIT.

package types

import "time"


// Attachment — Attachment a generic attachment
type Attachment struct {
	Created time.Time `json:"created_at,omitempty"`
	DownloadCount int64 `json:"download_count,omitempty"`
	DownloadURL string `json:"browser_download_url,omitempty"`
	ID int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Size int64 `json:"size,omitempty"`
	Type string `json:"type,omitempty"`
	UUID string `json:"uuid,omitempty"`
}

// EditAttachmentOptions — EditAttachmentOptions options for editing attachments
type EditAttachmentOptions struct {
	DownloadURL string `json:"browser_download_url,omitempty"` // (Can only be set if existing attachment is of external type)
	Name string `json:"name,omitempty"`
}

// Permission — Permission represents a set of permissions
type Permission struct {
	Admin bool `json:"admin,omitempty"`
	Pull bool `json:"pull,omitempty"`
	Push bool `json:"push,omitempty"`
}

// StateType — StateType issue state type
// StateType has no fields in the swagger spec.
type StateType struct{}

// TimeStamp — TimeStamp defines a timestamp
// TimeStamp has no fields in the swagger spec.
type TimeStamp struct{}

