// Code generated by forgegen from swagger.v1.json — DO NOT EDIT.

package types

import "time"


type AccessToken struct {
	ID int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Scopes []string `json:"scopes,omitempty"`
	Token string `json:"sha1,omitempty"`
	TokenLastEight string `json:"token_last_eight,omitempty"`
}

// CreateAccessTokenOption — CreateAccessTokenOption options when create access token
type CreateAccessTokenOption struct {
	Name string `json:"name"`
	Scopes []string `json:"scopes,omitempty"`
}

// CreateOAuth2ApplicationOptions — CreateOAuth2ApplicationOptions holds options to create an oauth2 application
type CreateOAuth2ApplicationOptions struct {
	ConfidentialClient bool `json:"confidential_client,omitempty"`
	Name string `json:"name,omitempty"`
	RedirectURIs []string `json:"redirect_uris,omitempty"`
}

type OAuth2Application struct {
	ClientID string `json:"client_id,omitempty"`
	ClientSecret string `json:"client_secret,omitempty"`
	ConfidentialClient bool `json:"confidential_client,omitempty"`
	Created time.Time `json:"created,omitempty"`
	ID int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	RedirectURIs []string `json:"redirect_uris,omitempty"`
}

