// Code generated by forgegen from swagger.v1.json — DO NOT EDIT.

package types

import "time"


// EditReactionOption — EditReactionOption contain the reaction type
type EditReactionOption struct {
	Reaction string `json:"content,omitempty"`
}

// Reaction — Reaction contain one reaction
type Reaction struct {
	Created time.Time `json:"created_at,omitempty"`
	Reaction string `json:"content,omitempty"`
	User *User `json:"user,omitempty"`
}

