// Code generated by forgegen from swagger.v1.json — DO NOT EDIT.

package types


// ReviewStateType — ReviewStateType review state type
// ReviewStateType has no fields in the swagger spec.
type ReviewStateType struct{}
