// Code generated by forgegen from swagger.v1.json — DO NOT EDIT.

package types

// CombinedStatus — CombinedStatus holds the combined state of several statuses for a single commit
type CombinedStatus struct {
	CommitURL  string             `json:"commit_url,omitempty"`
	Repository *Repository        `json:"repository,omitempty"`
	SHA        string             `json:"sha,omitempty"`
	State      *CommitStatusState `json:"state,omitempty"`
	Statuses   []*CommitStatus    `json:"statuses,omitempty"`
	TotalCount int64              `json:"total_count,omitempty"`
	URL        string             `json:"url,omitempty"`
}

// CreateStatusOption — CreateStatusOption holds the information needed to create a new CommitStatus for a Commit
type CreateStatusOption struct {
	Context     string             `json:"context,omitempty"`
	Description string             `json:"description,omitempty"`
	State       *CommitStatusState `json:"state,omitempty"`
	TargetURL   string             `json:"target_url,omitempty"`
}
