// Code generated by forgegen from swagger.v1.json — DO NOT EDIT.

package types


// CreateTeamOption — CreateTeamOption options for creating a team
type CreateTeamOption struct {
	CanCreateOrgRepo bool `json:"can_create_org_repo,omitempty"`
	Description string `json:"description,omitempty"`
	IncludesAllRepositories bool `json:"includes_all_repositories,omitempty"`
	Name string `json:"name"`
	Permission string `json:"permission,omitempty"`
	Units []string `json:"units,omitempty"`
	UnitsMap map[string]any `json:"units_map,omitempty"`
}

// EditTeamOption — EditTeamOption options for editing a team
type EditTeamOption struct {
	CanCreateOrgRepo bool `json:"can_create_org_repo,omitempty"`
	Description string `json:"description,omitempty"`
	IncludesAllRepositories bool `json:"includes_all_repositories,omitempty"`
	Name string `json:"name"`
	Permission string `json:"permission,omitempty"`
	Units []string `json:"units,omitempty"`
	UnitsMap map[string]any `json:"units_map,omitempty"`
}

// Team — Team represents a team in an organization
type Team struct {
	CanCreateOrgRepo bool `json:"can_create_org_repo,omitempty"`
	Description string `json:"description,omitempty"`
	ID int64 `json:"id,omitempty"`
	IncludesAllRepositories bool `json:"includes_all_repositories,omitempty"`
	Name string `json:"name,omitempty"`
	Organization *Organization `json:"organization,omitempty"`
	Permission string `json:"permission,omitempty"`
	Units []string `json:"units,omitempty"`
	UnitsMap map[string]any `json:"units_map,omitempty"`
}

