// Code generated by forgegen from swagger.v1.json — DO NOT EDIT.

package types

import "time"


// TopicName — TopicName a list of repo topic names
type TopicName struct {
	TopicNames []string `json:"topics,omitempty"`
}

// TopicResponse — TopicResponse for returning topics
type TopicResponse struct {
	Created time.Time `json:"created,omitempty"`
	ID int64 `json:"id,omitempty"`
	Name string `json:"topic_name,omitempty"`
	RepoCount int64 `json:"repo_count,omitempty"`
	Updated time.Time `json:"updated,omitempty"`
}
