// Code generated by forgegen from swagger.v1.json — DO NOT EDIT.

package types

import "time"


type BlockedUser struct {
	BlockID int64 `json:"block_id,omitempty"`
	Created time.Time `json:"created_at,omitempty"`
}

// CreateEmailOption — CreateEmailOption options when creating email addresses
//
// Usage:
//
//	opts := CreateEmailOption{Emails: []string{"example"}}
type CreateEmailOption struct {
	Emails []string `json:"emails,omitempty"` // email addresses to add
}

// CreateUserOption — CreateUserOption create user options
//
// Usage:
//
//	opts := CreateUserOption{Email: "alice@example.com"}
type CreateUserOption struct {
	Created time.Time `json:"created_at,omitempty"` // For explicitly setting the user creation timestamp. Useful when users are migrated from other systems. When omitted, the user's creation timestamp will be set to "now".
	Email string `json:"email"`
	FullName string `json:"full_name,omitempty"`
	LoginName string `json:"login_name,omitempty"`
	MustChangePassword bool `json:"must_change_password,omitempty"`
	Password string `json:"password,omitempty"`
	Restricted bool `json:"restricted,omitempty"`
	SendNotify bool `json:"send_notify,omitempty"`
	SourceID int64 `json:"source_id,omitempty"`
	Username string `json:"username"`
	Visibility string `json:"visibility,omitempty"`
}

// DeleteEmailOption — DeleteEmailOption options when deleting email addresses
//
// Usage:
//
//	opts := DeleteEmailOption{Emails: []string{"example"}}
type DeleteEmailOption struct {
	Emails []string `json:"emails,omitempty"` // email addresses to delete
}

// EditUserOption — EditUserOption edit user options
//
// Usage:
//
//	opts := EditUserOption{Description: "example"}
type EditUserOption struct {
	Active bool `json:"active,omitempty"`
	Admin bool `json:"admin,omitempty"`
	AllowCreateOrganization bool `json:"allow_create_organization,omitempty"`
	AllowGitHook bool `json:"allow_git_hook,omitempty"`
	AllowImportLocal bool `json:"allow_import_local,omitempty"`
	Description string `json:"description,omitempty"`
	Email string `json:"email,omitempty"`
	FullName string `json:"full_name,omitempty"`
	Location string `json:"location,omitempty"`
	LoginName string `json:"login_name,omitempty"`
	MaxRepoCreation int64 `json:"max_repo_creation,omitempty"`
	MustChangePassword bool `json:"must_change_password,omitempty"`
	Password string `json:"password,omitempty"`
	ProhibitLogin bool `json:"prohibit_login,omitempty"`
	Pronouns string `json:"pronouns,omitempty"`
	Restricted bool `json:"restricted,omitempty"`
	SourceID int64 `json:"source_id,omitempty"`
	Visibility string `json:"visibility,omitempty"`
	Website string `json:"website,omitempty"`
}

// Email — Email an email address belonging to a user
type Email struct {
	Email string `json:"email,omitempty"`
	Primary bool `json:"primary,omitempty"`
	UserID int64 `json:"user_id,omitempty"`
	UserName string `json:"username,omitempty"`
	Verified bool `json:"verified,omitempty"`
}

// SetUserQuotaGroupsOptions — SetUserQuotaGroupsOptions represents the quota groups of a user
//
// Usage:
//
//	opts := SetUserQuotaGroupsOptions{Groups: []string{"example"}}
type SetUserQuotaGroupsOptions struct {
	Groups []string `json:"groups"` // Quota groups the user shall have
}

// UpdateUserAvatarOption — UpdateUserAvatarUserOption options when updating the user avatar
//
// Usage:
//
//	opts := UpdateUserAvatarOption{Image: "example"}
type UpdateUserAvatarOption struct {
	Image string `json:"image,omitempty"` // image must be base64 encoded
}

// User — User represents a user
type User struct {
	AvatarURL string `json:"avatar_url,omitempty"` // URL to the user's avatar
	Created time.Time `json:"created,omitempty"`
	Description string `json:"description,omitempty"` // the user's description
	Email string `json:"email,omitempty"`
	Followers int64 `json:"followers_count,omitempty"` // user counts
	Following int64 `json:"following_count,omitempty"`
	FullName string `json:"full_name,omitempty"` // the user's full name
	HTMLURL string `json:"html_url,omitempty"` // URL to the user's gitea page
	ID int64 `json:"id,omitempty"` // the user's id
	IsActive bool `json:"active,omitempty"` // Is user active
	IsAdmin bool `json:"is_admin,omitempty"` // Is the user an administrator
	Language string `json:"language,omitempty"` // User locale
	LastLogin time.Time `json:"last_login,omitempty"`
	Location string `json:"location,omitempty"` // the user's location
	LoginName string `json:"login_name,omitempty"` // the user's authentication sign-in name.
	ProhibitLogin bool `json:"prohibit_login,omitempty"` // Is user login prohibited
	Pronouns string `json:"pronouns,omitempty"` // the user's pronouns
	Restricted bool `json:"restricted,omitempty"` // Is user restricted
	SourceID int64 `json:"source_id,omitempty"` // The ID of the user's Authentication Source
	StarredRepos int64 `json:"starred_repos_count,omitempty"`
	UserName string `json:"login,omitempty"` // the user's username
	Visibility string `json:"visibility,omitempty"` // User visibility level option: public, limited, private
	Website string `json:"website,omitempty"` // the user's website
}

// UserHeatmapData — UserHeatmapData represents the data needed to create a heatmap
type UserHeatmapData struct {
	Contributions int64 `json:"contributions,omitempty"`
	Timestamp *TimeStamp `json:"timestamp,omitempty"`
}

// UserSettings — UserSettings represents user settings
type UserSettings struct {
	Description string `json:"description,omitempty"`
	DiffViewStyle string `json:"diff_view_style,omitempty"`
	EnableRepoUnitHints bool `json:"enable_repo_unit_hints,omitempty"`
	FullName string `json:"full_name,omitempty"`
	HideActivity bool `json:"hide_activity,omitempty"`
	HideEmail bool `json:"hide_email,omitempty"` // Privacy
	Language string `json:"language,omitempty"`
	Location string `json:"location,omitempty"`
	Pronouns string `json:"pronouns,omitempty"`
	Theme string `json:"theme,omitempty"`
	Website string `json:"website,omitempty"`
}

// UserSettingsOptions — UserSettingsOptions represents options to change user settings
//
// Usage:
//
//	opts := UserSettingsOptions{Description: "example"}
type UserSettingsOptions struct {
	Description string `json:"description,omitempty"`
	DiffViewStyle string `json:"diff_view_style,omitempty"`
	EnableRepoUnitHints bool `json:"enable_repo_unit_hints,omitempty"`
	FullName string `json:"full_name,omitempty"`
	HideActivity bool `json:"hide_activity,omitempty"`
	HideEmail bool `json:"hide_email,omitempty"` // Privacy
	Language string `json:"language,omitempty"`
	Location string `json:"location,omitempty"`
	Pronouns string `json:"pronouns,omitempty"`
	Theme string `json:"theme,omitempty"`
	Website string `json:"website,omitempty"`
}
